# -*- coding: utf-8 -*-
"""01_Introduction_to_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sxw3TaV2ogIdXY46cbsjJWEf8iK4Q5zx

# Introduction to Python ![Python Logo](https://www.python.org/static/community_logos/python-logo.png)

Python is a high-level, interpreted programming language created by Guido van Rossum and first released in 1991. It has gained immense popularity due to its readability, simplicity, and vast ecosystem, making it suitable for various applications ranging from web development to artificial intelligence.

## Key Features of Python

### 1. 📖 **Readability**
Python's syntax emphasizes readability, allowing developers to express concepts in fewer lines of code than in other languages like C++ or Java.
"""

# Simple Python code to print "Hello, World!"
print("Hello, World!")

"""
### 2. 💻 **Interpreted Language**
Python is interpreted, meaning that code is executed line-by-line. This feature aids in debugging and development speed but can impact runtime performance.

### 3. 🔄 **Dynamic Typing**
In Python, types are determined at runtime, providing flexibility in coding. However, this can sometimes lead to runtime errors if not managed carefully.
"""

x = 10      # x is an integer
x = "Hello" # Now, x is a string

"""
### 4. 📚 **Extensive Standard Library**
Python’s standard library supports many common programming tasks such as file I/O, system calls, and even Internet protocols. This reduces the need for external libraries for many tasks.
"""

import os

# List files in the current directory
print(os.listdir('.'))

"""
### 5. 🧩 **Support for Multiple Paradigms**
Python supports procedural, object-oriented, and functional programming paradigms, making it a versatile tool for various types of projects.

### 6. 🌐 **Community and Ecosystem**
Python's large, active community and extensive ecosystem of third-party packages enhance its functionality and usability. The Python Package Index (PyPI) hosts thousands of packages that extend Python's capabilities.

## Popular Uses of Python

### 📊 Data Science
Python is a favorite among data scientists due to libraries like NumPy, pandas, and Matplotlib. These libraries provide robust tools for data analysis, manipulation, and visualization.

### 🌐 Web Development
Frameworks such as Django and Flask make Python a powerful choice for web development. These frameworks simplify the development process by providing reusable code and components.

### 🤖 Automation
Python excels in scripting and automation tasks. Tools like Selenium for web automation and Beautiful Soup for web scraping are popular among developers for automating repetitive tasks.

### 🧠 Artificial Intelligence
Libraries such as TensorFlow and PyTorch facilitate the development of AI and machine learning models, allowing Python to dominate the AI research and development space.

## Getting Started with Python

### Installation
Python can be downloaded from the official [Python website](https://www.python.org/). Installation instructions are available for Windows, macOS, and Linux.

### Writing Your First Python Program

1. **Open a text editor or IDE.**
2. **Type the following code:**
"""

print("Hello, Python!")

"""
3. **Save the file with a `.py` extension.**
4. **Run the program from the command line:**
"""

python your_program.py

"""
### Conclusion
Python's combination of simplicity, readability, and a powerful standard library makes it an excellent choice for both novice and experienced developers. Its widespread use in various domains such as web development, data science, and AI underlines its versatility and effectiveness as a programming language.

### 📢 Stay Updated
Be sure to ⭐ this repository to stay updated with new examples and enhancements!

### 📄 License
🔐 This project is protected under the [MIT License](https://mit-license.org/).

### Contact 📧
Panagiotis Moschos - pan.moschos86@gmail.com

🔗 *Note: This is a Python script and requires a Python interpreter to run.*

---

<h1 align=center>Happy Coding 👨‍💻 </h1>

<p align="center">
  Made with ❤️ by Panagiotis Moschos (https://github.com/pmoschos)
</p>"""